apiVersion: v1
appVersion: "0.4.0"
description: Podinfo Helm chart for Kubernetes
name: podinfo
version: 0.2.2
home: https://github.com/derek-ooohtv/k8s-podinfo
sources:
- https://github.com/derek-ooohtv/k8s-podinfo
maintainers:
  - name: derek-ooohtv
    email: derek-ooohtv@users.noreply.github.com
engine: gotpl
